### ISSUE TITLE
Simeta is working or not?

### ISSUE THREAD

**Issue by magibc** [softloud/simeta#34]
Hi
I have checked that Metasim has been moved to simeta. Nevertheless, I saw that the readme is in progress. Therefore, I understand that is not possible to generate metagenomic simulated datasets?

Thanks on advance,

**Comment by softloud** [comment]
Hiya, I've just done a big update (took me a while to come out from my phd recovery period to return to this software, apologies). I have a colleague who is using the software, and have just [rewritten the documentation](https://softloud.github.io/simeta) around his use case. Specifically, the datasets that are generated are meta-analysis datasets, as in they simulate underlying samples for each arm of a control/intervention study, and produce a dataset in the format useful to metafor (this can be adapted to other meta-analysis software with a little engineering). Do reopen if you find anything useful/are still looking.
